# MySQL JDBC Driver
db.driver=com.mysql.cj.jdbc.Driver

# MySQL Database URL
db.url=jdbc:mysql://localhost:3306/insurance_management?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

# MySQL Username
db.username=root

# MySQL Password
db.password=crimsonlogic@123